### ISSUE TITLE
add event handlers

### ISSUE THREAD

**Issue by voronp** [oliverfindl/vue-svg-inline-plugin#11]
it drops event handlers right now, for instance, @click="onClick" not triggering

**Comment by oliverfindl** [comment]
Hello,

this is known issue of this package. This plugin is replacing original image node with new SVG node. I didn't found a way to transfer / clone [Vue](https://github.com/vuejs/vue-next) bindings from image node to SVG node. Therefore this won't work. As workaround, you can bind your event listener to wrapper of this image / SVG node.

If you have any more questions, feel free to ask here.

Thanks.

**Comment by oliverfindl** [comment]
Closing this issue.
