### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by iandevlin** [oliverfindl/vue-svg-inline-plugin#7]
Hi, this is more of a question than an "issue".
First of all thank you for your work on both this and on `vue-svg-inline-loader`.

I found a thread on `vue-svg-inline-loader` that mentioned that this new plugin supports the first dynamic value in the `:src` attribute, but I don't see any examples of how that should work.

I am trying to use it but it doesn't work, so I assume I am doing something wrong so an example of what you meant would be great.

e.g. from what you wrote I would expect something like: ``<img v-svg-inline :src="`./assets/icons/${icon}.svg`" />`` to work, but I've probably misunderstood what you meant.

Thanks in advance!

**Comment by oliverfindl** [comment]
Hello,

I just tried your code in my [browser vue@3 example](https://github.com/oliverfindl/vue-svg-inline-plugin/tree/master/examples/browser-vue3), and its working for me. Most probably you have issue with path to SVG file and/or misconfigured bundler. Try to open DevTools in your browser, switch to network tab and filter all SVG requests.

Alternatively, if you cannot figure it out, try to create minimal repo, where you are encountering this issue.

Thanks.

**Comment by iandevlin** [comment]
Hi,

yeah it could be, although if I used the wrong path it complained that it couldn't find the SVG file.

I found a different solution for now though, so thank you for your reply but I will close this as it probably was something I was doing wrong.

Thank you again!
